events:
  - Test
http: "Golang YAML"
  include: mime.types
  default_type: application/pctet-stream;
  sendfile: on;
  keepalive_timeout: 65;
  - server:
		  listen:          8080;
		  server_name:     localhost;
		  location: 
			  root:          html;
			  index:         index.html index.htm;
